name: readme

on:

  push:
    branches: [ main ]
    paths:
      - README.md

  pull_request:
    branches: [ main ]
    paths:
      - README.md

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: gwaroquier/docker-centos7-fr
